import { CompanyJob, HelpOffer, HelpRequest, JobApplication, ChatThread, ChatMessage } from "./types";

export const seedRequests: HelpRequest[] = [
  {
    id: "r1",
    authorId: "u-pf-1",
    authorName: "Mariana Silva",
    authorType: "individual",
    title: "Montagem de móveis IKEA - guarda-roupa 4 portas",
    description: "Preciso de alguém com experiência para montar um guarda-roupa grande. Já está na sala. Tenho ferramentas básicas.",
    category: "reparos",
    budget: 280,
    city: "São Paulo",
    neighborhood: "Pinheiros",
    scheduledAt: "2025-05-02T14:00",
    createdAt: "2025-04-22T10:00",
    proposalsCount: 7,
  },
  {
    id: "r2",
    authorId: "u-pj-1",
    authorName: "Café Aurora",
    authorType: "company",
    title: "Limpeza pós-obra em cafeteria (80m²)",
    description: "Limpeza pesada após reforma. Remoção de tinta, poeira de gesso, polimento de piso. Material por nossa conta.",
    category: "limpeza",
    budget: 950,
    city: "São Paulo",
    neighborhood: "Vila Madalena",
    scheduledAt: "2025-04-29T08:00",
    createdAt: "2025-04-23T09:30",
    proposalsCount: 12,
  },
  {
    id: "r3",
    authorId: "u-pf-2",
    authorName: "Rafael Costa",
    authorType: "individual",
    title: "Aulas particulares de inglês conversação",
    description: "Busco professor para aulas semanais (2h) com foco em business english. Online ou presencial.",
    category: "aulas",
    budget: 120,
    city: "Rio de Janeiro",
    neighborhood: "Ipanema",
    scheduledAt: "2025-05-05T19:00",
    createdAt: "2025-04-23T15:20",
    proposalsCount: 4,
  },
  {
    id: "r4",
    authorId: "u-pj-2",
    authorName: "Studio Norte Eventos",
    authorType: "company",
    title: "Fotógrafo para evento corporativo (4h)",
    description: "Cobertura fotográfica de lançamento de produto. ~80 convidados, ambiente interno bem iluminado.",
    category: "eventos",
    budget: 1800,
    city: "Belo Horizonte",
    neighborhood: "Savassi",
    scheduledAt: "2025-05-10T18:00",
    createdAt: "2025-04-24T11:00",
    proposalsCount: 9,
  },
  {
    id: "r5",
    authorId: "u-pf-3",
    authorName: "Camila Duarte",
    authorType: "individual",
    title: "Manutenção de ar-condicionado split 12.000",
    description: "Limpeza completa e checagem de gás. Aparelho com 2 anos, no quarto.",
    category: "reparos",
    budget: 220,
    city: "Curitiba",
    neighborhood: "Batel",
    scheduledAt: "2025-04-30T10:00",
    createdAt: "2025-04-24T16:45",
    proposalsCount: 3,
  },
  {
    id: "r6",
    authorId: "u-pj-3",
    authorName: "Boutique Lumière",
    authorType: "company",
    title: "Designer para criação de identidade visual",
    description: "Logo, paleta de cores e manual de marca para boutique de roupas premium. Briefing pronto.",
    category: "design",
    budget: 2400,
    city: "São Paulo",
    neighborhood: "Jardins",
    scheduledAt: "2025-05-12T10:00",
    createdAt: "2025-04-25T08:10",
    proposalsCount: 18,
  },
];

export const seedOffers: HelpOffer[] = [
  {
    id: "o1",
    freelancerId: "u-fl-1",
    freelancerName: "Lucas Andrade",
    rating: 4.9,
    reviews: 128,
    serviceName: "Eletricista residencial certificado",
    description: "10 anos de experiência. Instalações, reparos, quadros de luz, automação básica. NR-10.",
    category: "reparos",
    pricing: { type: "hour", value: 95 },
    coverage: "Zona Oeste de SP — até 15km",
    city: "São Paulo",
  },
  {
    id: "o2",
    freelancerId: "u-fl-2",
    freelancerName: "Patrícia Mendes",
    rating: 5.0,
    reviews: 64,
    serviceName: "Diarista especializada em pós-obra",
    description: "Equipe própria, produtos profissionais inclusos. Atendo residências e comércios.",
    category: "limpeza",
    pricing: { type: "fixed", value: 350 },
    coverage: "Grande SP",
    city: "São Paulo",
  },
  {
    id: "o3",
    freelancerId: "u-fl-3",
    freelancerName: "Diego Ramos",
    rating: 4.8,
    reviews: 91,
    serviceName: "Designer gráfico — branding & social",
    description: "Identidades visuais completas e gestão de design para redes. Adobe + Figma.",
    category: "design",
    pricing: { type: "fixed", value: 1800 },
    coverage: "Remoto — Brasil",
    city: "Florianópolis",
  },
  {
    id: "o4",
    freelancerId: "u-fl-4",
    freelancerName: "Beatriz Nogueira",
    rating: 4.9,
    reviews: 47,
    serviceName: "Professora de inglês & espanhol",
    description: "Cambridge CELTA. Aulas particulares e corporativas, foco em fluência.",
    category: "aulas",
    pricing: { type: "hour", value: 110 },
    coverage: "Online + Rio de Janeiro",
    city: "Rio de Janeiro",
  },
  {
    id: "o5",
    freelancerId: "u-fl-5",
    freelancerName: "Henrique Lopes",
    rating: 4.7,
    reviews: 33,
    serviceName: "Suporte técnico e redes",
    description: "Configuração de redes, formatação, recuperação de dados, instalação de sistemas.",
    category: "tecnologia",
    pricing: { type: "hour", value: 85 },
    coverage: "Curitiba e região",
    city: "Curitiba",
  },
  {
    id: "o6",
    freelancerId: "u-fl-6",
    freelancerName: "Sofia Almeida",
    rating: 5.0,
    reviews: 152,
    serviceName: "Fotógrafa de eventos & corporativo",
    description: "Equipamento profissional, entrega em até 7 dias. Cobertura BH/SP.",
    category: "eventos",
    pricing: { type: "fixed", value: 2200 },
    coverage: "BH + viagens",
    city: "Belo Horizonte",
  },
];

export const seedJobs: CompanyJob[] = [
  {
    id: "j1",
    companyId: "u-pj-1",
    companyName: "Café Aurora",
    title: "Barista Pleno",
    description: "Buscamos barista com experiência em café especial e latte art. Turno integral.",
    category: "outros",
    salary: "R$ 2.800 + benefícios",
    city: "São Paulo",
    modality: "presencial",
    status: "open",
    createdAt: "2025-04-20",
  },
  {
    id: "j2",
    companyId: "u-pj-2",
    companyName: "Studio Norte Eventos",
    title: "Assistente de Produção",
    description: "Apoio em montagem, logística de fornecedores e atendimento durante eventos.",
    category: "eventos",
    salary: "R$ 2.400",
    city: "Belo Horizonte",
    modality: "hibrido",
    status: "open",
    createdAt: "2025-04-22",
  },
  {
    id: "j3",
    companyId: "u-pj-3",
    companyName: "Boutique Lumière",
    title: "Vendedor(a) de moda premium",
    description: "Atendimento consultivo, gestão de estoque e visual merchandising.",
    category: "outros",
    salary: "R$ 2.200 + comissão",
    city: "São Paulo",
    modality: "presencial",
    status: "open",
    createdAt: "2025-04-24",
  },
];

export const seedApplications: JobApplication[] = [
  { id: "a1", jobId: "j1", candidateId: "c1", candidateName: "Júlia Ferraz", candidateHeadline: "Barista Sênior • 5 anos", status: "review", appliedAt: "2025-04-21" },
  { id: "a2", jobId: "j1", candidateId: "c2", candidateName: "Marcos Vinicius", candidateHeadline: "Atendente de cafeteria", status: "pending", appliedAt: "2025-04-22" },
  { id: "a3", jobId: "j1", candidateId: "c3", candidateName: "Aline Souza", candidateHeadline: "Latte art champion local", status: "hired", appliedAt: "2025-04-22" },
  { id: "a4", jobId: "j1", candidateId: "c4", candidateName: "Eduardo Lima", candidateHeadline: "Garçom — 3 anos", status: "rejected", appliedAt: "2025-04-23" },
  { id: "a5", jobId: "j2", candidateId: "c5", candidateName: "Renata Pires", candidateHeadline: "Produtora cultural", status: "review", appliedAt: "2025-04-23" },
  { id: "a6", jobId: "j2", candidateId: "c6", candidateName: "Pedro Henrique", candidateHeadline: "Logística de eventos", status: "pending", appliedAt: "2025-04-24" },
  { id: "a7", jobId: "j3", candidateId: "c7", candidateName: "Tainá Oliveira", candidateHeadline: "Consultora de moda", status: "pending", appliedAt: "2025-04-25" },
];

export const seedThreads: ChatThread[] = [
  { id: "t1", participantId: "u-fl-1", participantName: "Lucas Andrade", topic: "Instalação de chuveiro elétrico", lastMessageAt: "2025-04-25T10:24" },
  { id: "t2", participantId: "u-fl-3", participantName: "Diego Ramos", topic: "Identidade visual - boutique", lastMessageAt: "2025-04-24T18:02" },
  { id: "t3", participantId: "u-fl-6", participantName: "Sofia Almeida", topic: "Cobertura evento corporativo", lastMessageAt: "2025-04-23T14:45" },
];

export const seedMessages: Record<string, ChatMessage[]> = {
  t1: [
    { id: "m1", threadId: "t1", fromId: "u-fl-1", text: "Olá! Posso atender amanhã às 14h. Material por minha conta?", at: "2025-04-25T10:20" },
    { id: "m2", threadId: "t1", fromId: "me", text: "Perfeito Lucas. Pode trazer o material e me passa o orçamento.", at: "2025-04-25T10:24" },
  ],
  t2: [
    { id: "m3", threadId: "t2", fromId: "u-fl-3", text: "Enviei a primeira leva de moodboards no email.", at: "2025-04-24T18:02" },
  ],
  t3: [
    { id: "m4", threadId: "t3", fromId: "u-fl-6", text: "Confirmado para o dia 10! Levo dois fotógrafos.", at: "2025-04-23T14:45" },
  ],
};
